### ISSUE TITLE
After a Find operation, selected text stays highlighted in yellow, until a future Find

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#13]
After doing a Find text operation, the text that gets highlighted in yellow, remains highlighted no matter what is done to move the cursor, try to select that or other text for editing, etc...

I think this also happens when a compiler error is found and the line of text in error is highlighted.

The highlight should be removed once the user does one of a number of different actions:

1. select the text for removal or in-line editing
2. move the cursor to another location and clicking
3. closing the Find dialog window
3. etc... probably a few other actions that should signal the end of the need for highlighting the found text.

**Comment by totalspectrum** [comment]
This one seems to be a bit tricky. I hope someone with a better knowledge of tcl/tk may be able to offer a suggestion.

**Comment by totalspectrum** [comment]
OK, at least the highlighting goes away now when you close the Find window, so that's an improvement.

**Comment by totalspectrum** [comment]
Since the highlighting does go away when Find is closed, I think this can be considered closed.
