### ISSUE TITLE
Listing file view doesn't copy text via Command-C on macOS (but, using the menu "Copy" works)

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#20]
In the flexgui editor: When a compiled listing window is displayed, the user can use the menu commands to Copy & Paste text to/from the listing window (and back to the source text window).

However, the Copy command does not function when the user applies Command-C to attempt text copying. In the example image, in the listing window, the text "she muldivb_, #16" has been selected and Command-C has been typed. Attempting to paste that text into the Search dialog, shows that a previously-copied text, "sub  objptr, #4" gets pasted. The same previously-copied text will paste into the source listing as well.

It appears that only the Command-C (Copy) command works incorrectly. Command-V, paste works as it should.

<img width="1119" alt="Cmd-Copy_Paste_Issue" src="https://user-images.githubusercontent.com/3009364/90338287-7b513300-df9d-11ea-8423-250f24a8bab4.png">

**Comment by totalspectrum** [comment]
This should work now
