### ISSUE TITLE
flexgui Cut menu enabled while un-editable text is selected in listing window

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#21]
In the flexgui editor: The Cut menu and Command-X features are disabled when selecting text within the listing window, which is as intended. But, the menu shows Cut as 'enabled'. The attached image shows how a typical application (Safari on macOS) disables the Cut menu when un-editable text is selected. 

<img width="619" alt="CutMenuDisabled" src="https://user-images.githubusercontent.com/3009364/90338580-7beac900-df9f-11ea-80a4-c7a21d9df03b.png">

**Comment by totalspectrum** [comment]
The listing window is actually editable now so that users may add comments if they wish.
