### ISSUE TITLE
Inconsistent naming in documentation files

### ISSUE THREAD

**Issue by jacgoudsmit** [totalspectrum/flexprop#23]
Hi Eric,

I noticed that some of the documentation files such as readme.md and help.txt mention "FlexPropGUI" as well as "FlexProp". There are also some places in the documentation where files are misnamed (e.g. they mention flexpropgui.zip instead of flexprop.zip).

The code appears to use "FlexProp" everywhere so probably the documentation needs to be updated to use "FlexProp" only, not "FlexPropGUI".

If you're interested, I can submit a Pull Request :-).

Thanks!

===Jac

**Comment by totalspectrum** [comment]
Thanks for the bug report! I think I've fixed those references now, but if you see any other inconsistencies please let me know. A pull request would be great :).

**Comment by jacgoudsmit** [comment]
No PR necessary. Looks like you got them all :-)
