### ISSUE TITLE
debug() not handled in pasm code

### ISSUE THREAD

**Issue by ironsheep** [totalspectrum/flexprop#25]
Just a tiny compatibility issue.

What are you planning to do with the debug() statements that Chip supports?

I just got a compile error "**error: syntax error, unexpected DEBUG**" for my having debug() statements in the DAT section (pasm2 code).

It would be nice not to have to comment these out as it would mean that I have to edit my code depending upon which compiler I'm using.

**Comment by totalspectrum** [comment]
I think it should be possible to ignore the DEBUG() statements in PASM code. For various reasons I doubt they'll ever do anything useful in flexspin. I'd rather see a proper single step debugger.

(DEBUG() does partially work in Spin2 code inside flexspin).

**Comment by totalspectrum** [comment]
debug() is ignored now in PASM code, as of 5.0.1
