### ISSUE TITLE
pasm using constants from external object not handled

### ISSUE THREAD

**Issue by ironsheep** [totalspectrum/flexprop#26]
Another for you. Trying to build and test my RGB LED matrix driver with your tools.
Just found this:

`mov panelCol, #screen.MAX_DISPLAY_COLUMNS`

Generates: **error: Operand too complex for inline assembly**

Guess I'm stopped at this point. BTW- I'm just working with spin2/pasm2 with these tests.

**Comment by totalspectrum** [comment]
Thanks for the bug report. I'll fix this soon.

**Comment by totalspectrum** [comment]
This should work now as of 5.0.1
