### ISSUE TITLE
cursor positioning in editor at mouse click highly inaccurate

### ISSUE THREAD

**Issue by ironsheep** [totalspectrum/flexprop#27]
Fun?? test.  

Attempt to position the cursor just ahead of the first character on an indented line.  Can take up to leading "number of spaces" tries (the cursor moves toward the desired position with every click?!).  That's a symptom I haven't seen before?! ;-)

I'm on macOS catalina v10.15.7 running flexprop from the .dmg build.
I wanted to provide a build version but I don't see a menu item offering an about screen or something similar.

You are making great progress!

Thanks for your work on this!

**Comment by totalspectrum** [comment]
That's very strange, and it seems to only happen on MacOS. It's probably a Tk bug, and so not likely that I can fix it. It does seem to be less of an issue with a larger font though.

BTW, the "About..." option under the Help menu shows the FlexProp version.

**Comment by totalspectrum** [comment]
I think this was indeed a Tk bug, and seems to be fixed with tk 8.6.12 (which is the version included with flexprop 5.9.6).
