### ISSUE TITLE
spin2cpp (and thus, flexprop) fails do build on current macOS version (bison on macOS is too old)

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#31]
Building flexprop (actually, the spin2cpp module) on current macOS version (version 11.0.1 Big Sur) results in:
```
~/source/flexprop/spin2cpp]$ make
bison -t -b ./build/spin -d frontends/spin/spin.y
frontends/spin/spin.y:7.9-18: syntax error, unexpected identifier, expecting string
make: *** [build/spin.tab.h] Error 1
```
standard bison version on that macOS is:
```
% bison -V
bison (GNU Bison) 2.3
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2006 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
In order to build spin2cpp, the workaround is to install bison from homebrew:

```
$ brew install bison
$ /usr/local/Cellar/bison/3.7.4/bin/bison -V
bison (GNU Bison) 3.7.4
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

AND, mod the spin2cpp Makefile with the following:
```
# note: to produce detailed debug, use YACC="bison --report=all"
YACC = /usr/local/Cellar/bison/3.7.4/bin/bison
#YACC = bison
#YACC = bison372
```

Probably not something to fix in spin2cpp or flexprop themselves, but a note about this in the README files for these projects would help. Also, this change must be made to the Makefile whenever the Makefile has been updated on github...

**Comment by totalspectrum** [comment]
There's a note in the spin2cpp README.md now. I really wish I could support the older bison version; it's not that we need any features of the new bison, it's just that the new bison has added some new variables that don't work properly with the way we were doing multiple parsers. And most Linux distros have updated to the new (IMHO broken) bison :(.

GNU hasn't provided any way to test bison version within the parser, and I don't really have time to try to finagle this in the Makefile. If you do come up with a solution I'd be happy to merge it, but for now it's "install a newer bison".
