### ISSUE TITLE
flexprop has issues compiling and running code in folders that contain commas

### ISSUE THREAD

**Issue by z80jon** [totalspectrum/flexprop#32]
This is the first Github issue I've ever opened, so please be a little lenient with me if I'm missing any details. I'm running the latest version of flexprop as of this writing, and for work I have almost all of my code inside a microsoft onedrive folder. I've found that FlexProp can open these files just fine, and can even compile them, but for whatever reason it cannot compile and run them on the P2--this is the error message I get when I try to do that (with personal info omitted)

> C:/Users/userName/Desktop/OneDrive - companyName: No such file or directory
Could not open C:/Users/userName/Desktop/OneDrive - companyName
Press enter to continue...

The actual code is a few folders in, but I THINK I know what the issue is. My onedrive folder is named (and I can't change it, because Microsoft) "OneDrive - Company Name, Inc", and given the error message, it seems flexprop really doesn't like the comma. (In windows you can't even put a comma in a folder name, so this is definitely an extremely rare edge case. hopefully, it isn't too hard to patch).

**Comment by totalspectrum** [comment]
Regrettably, this is not going to work. Commas are used in loadp2 to separate parameters, so a comma anywhere in a file name is not accepted. As you point out, this can only happen in onedrive, so I suggest you move your flexprop installation to a local drive.
