### ISSUE TITLE
flexprop editor tab-titles get very short with many open files, can't tell which file I'm editing

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#33]
When a large number (8, 10, 12, etc...?) of files are open for editing, the tabs get very small horizontally and the filenames get cut-down and it is difficult to know which actual file you are editing as you copy & rename files to add variant filenames (ex: "jm_i2c_driver" gets cloned to: "jm_i2c_driver_MOD"). I often quickly clone code from others (mostly JonnyMac :-) and add my initials or "MOD" to the filename. On occasion, I've started editing and realized I was editing the original file only after compiling/saving. Some way of know which actual file you are about to edit, would help with this problem.

![flexprop_tabs](https://user-images.githubusercontent.com/3009364/103445384-29e1d180-4c28-11eb-8beb-200ba5de58eb.jpg)

Could tooltips containing the filename be added? Then, as you move the cursor over a TAB, the full filename of the file is briefly displayed. 

I've seen that there are ways to add help text to TABs, but I'm unsure how to implement. Here's a stackoverflow posting which might provide some ideas about tab help text: [https://stackoverflow.com/questions/52352475/display-tooltip-when-hovering-on-a-tab](url)

**Comment by totalspectrum** [comment]
I've added some tool tips for the tabs. This is quite a hack, so it's not as smooth as I would like; it may take a few tries to get the tooltip to come up.

**Comment by totalspectrum** [comment]
I think this is working OK in 5.0.5.
