### ISSUE TITLE
Find... & Replace... should pre-select previous search text assist search-text edits

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#35]
When Find and/or Replace commands are executed more than once, the previously searched-for text is NOT selected/highlighted when the Find/Replace window is displayed. If the user needs to replace the search-text with new search criteria, they must click and drag (or even worse, type the 'delete-key' repetitively) to remove the previous search-text. If the previous search-text was already selected/highlighted, the user could just start typing new criteria or type the 'delete-key' once to remove old text.

I tested the following change to gui.tcl and it appears to work. I'm not sure if this is a total fix because of my own lack of tcl experience, so buyer-beware.

$ diff -c  gui.tcl gui.tcl.ORIG
*** gui.tcl	2021-02-01 08:35:34.000000000 -0800
--- gui.tcl.ORIG	2021-02-01 08:32:05.000000000 -0800
***************
*** 2023,2034 ****
         grid columnconfigure $w 1 -weight 1
         $t tag config hilite -background yellow
         focus $w.f
-        $w.f selection range 0 end
     } else {
         raise $w.f
         focus $w
         $w.f icursor end
-        $w.f selection range 0 end
     }
      bind $w <Destroy> "searchrep'done $t"
  }
--- 2023,2032 ----

![find_selection_test](https://user-images.githubusercontent.com/3009364/106490442-aefc1880-646a-11eb-9bd2-9e9f92eccba6.jpg)

**Comment by totalspectrum** [comment]
This looks like a nice change. Thanks, Dennis!

**Comment by dgately** [comment]
With this change in my sources, there are still occasions when previous search text shows up as un-selected. I have not quite figured out what sequence of events causes that, but will update or write another issue when I do!

**Comment by totalspectrum** [comment]
Forgot to close this one when we fixed it!
