### ISSUE TITLE
flexprop's editor should accept triple-clicks to select a full line of text

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#36]
When editing in most editors on modern operating systems (macOS. Linux, WIN10) a triple click in a text edit field or editable text window will select the entire line of text. This really helps when editing and wanting to replace a line of text or remove it, quickly. I often find myself triple-clicking in flexprop only to realize that I did not get a fully selected line and my editing needs to stop and retrace what I meant to happen :-)

There is tcl library code within the flexprop sources that does handle triple clicks: 
./tcl_library/tk8.7/text.tcl 
./tcl_library/tk8.7/ttk/entry.tcl
./tcl_library/tk8.7/entry.tcl

**Comment by totalspectrum** [comment]
Triple clicks seem to work OK for me on Linux. And Windows is using those library functions, so I'm sure they work there. I guess triple clicks were added in tk8.6, but your Mac only has tk8.5? 

The long term solution is probably to build tk from source for Mac, like we do for Windows. But this will only exacerbate the Gatekeeper problems people run into :(.

**Comment by dgately** [comment]
My Mac has tk8.6.9... Building an 8.7 variant might fix the problem, but as you say, may bring Gatekeeper issues... I may look into building 8.7 just to research this.

**Comment by totalspectrum** [comment]
Hmmm, that's odd. My linux is using tk 8.6 as well, and accepts triple clicks just fine. My Mac still has an old tk, so I had just assumed it was a tk version issue, but maybe it's a failing of tk on the Mac :(.

**Comment by dgately** [comment]
with macOS 11.5.2, and tcl-tk 8.6, triple-clicks seem to work now!

**Comment by dgately** [comment]
macOS 11.5.2 & tcl-tk 8.6 seem to allow triple-clicks!
