### ISSUE TITLE
flexprop.exe not closing

### ISSUE THREAD

**Issue by rosco-pc** [totalspectrum/flexprop#37]
For testing a P2D2 board I downloaded flexprop 5.0.8 on my windows (work) laptop. Closing the app is not working and shows the below error message

![image](https://user-images.githubusercontent.com/1007932/107919641-f787fb80-6f6b-11eb-81a8-5a52d774844f.png)

Note that the app is started from C: drive (C:\Users\<user>\Downloads\flexprop) and that no changes have been made after extraction

Only way to quit is to end the task through the task manager.

**Comment by totalspectrum** [comment]
It appears that the HOME environment variable is pointing to H:, but for some reason we can't write a file there. Does the drive H: exist?

I'll add some additional sanity checks, but for now a work-around would be to start flexprop from a batch file that sets HOME to some known good directory (like C:\Users\<users>\Downloads\flexprop).

Thanks for the bug report.

**Comment by totalspectrum** [comment]
Sanity check is there in the current github, and will be in the next release (coming Real Soon Now).

**Comment by rosco-pc** [comment]
Sorry for late reply, you're right
HOMEDRIVE is set to H: (that is a left over from the time we still had a remote home drive at work, since quite sometime not used anymore. But apparently they never removed these settings 😞)

Actually for windows you would normally use LOCALAPPDATA or USERPROFILE to find a place to store user preferences. I've not seen any windows software use HOMEDRIVE/HOMEPATH for a long time now

**Comment by totalspectrum** [comment]
I forgot the most obvious work-around, which is to create an empty .flexprop.config file in your flexprop folder (next to flexprop.exe). If one is found, the installation is assumed to be "portable" and the config file is written to there.
