### ISSUE TITLE
Using "-SINGLE" mode for loadp2 wont allow successful FLASH upload

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#39]
When trying to "Compile and Flash" in flexprop, while using the "-SINGLE" upload mode (required at this time with Cluso's RetroBlade2 board), loadp2 fails to find the binary file...

==========================================================================
Note: These examples were run on a P2Edge as Cluso's RetroBlade2 fails to load without "-SINGLE"
           An issue that will be written-up separately...
==========================================================================

Compiler/Loader output from flexprop (with the -SINGLE option):
$ /Users/altergator/flexprop/bin/loadp2 -p /dev/cu.usbserial-P6mhwic9 -b230400 @0=/Users/altergator/flexprop/board/P2ES_flashloader.bin,@8000+/Users/altergator/Documents/P2ESCode/StingrayP2/stingrayController.binary -T -k -SINGLE; osascript -e 'tell application "Wish" to activate'; exit 0
@0=/Users/altergator/flexprop/board/P2ES_flashloader.bin,@8000+/Users/altergator/Documents/P2ESCode/StingrayP2/stingrayController.binary: No such file or directory
Press enter to continue...

Compiler/Loader output from flexprop (removed -SINGLE option):
$ /Users/altergator/flexprop/bin/loadp2 -p /dev/cu.usbserial-P6mhwic9 -b230400 @0=/Users/altergator/flexprop/board/P2ES_flashloader.bin,@8000+/Users/altergator/Documents/P2ESCode/StingrayP2/stingrayController.binary -T -k; osascript -e 'tell application "Wish" to activate'; exit 0
( Entering terminal mode.  Press Ctrl-] to exit. )
P2-ES Flash Programmer
Erasing flash...
Programming...
Done
Saving session...completed.

Running the same commands on the command line result in the same issue... Seems to be a loadp2 problem, unless the -SINGLE mode is reserved for RAM uploads only.

**Comment by totalspectrum** [comment]
This is a feature, unfortunately. -SINGLE is only able to load a single file, and flash programming requires multiple files, so -SINGLE will not work with flash programming, only with RAM.
