### ISSUE TITLE
Spin2 Local Variables not initialized on entry into method()

### ISSUE THREAD

**Issue by francisbauer** [totalspectrum/flexprop#41]
In FlexProp 5.3.0-beta,  while checking on how much new DEBUG abilities were available, I noticed that local variables in a method() don't get initialized to zero.  Both PNut_v35j and PropTool 2.5.3 do initialize local variables to zero on entry to the method().  This could create confusion between the usage of these tools...

I've attached a zip file containing a source code example and DEBUG screenshots for each of the three tools: PNut_v35j, PropTool_2.5.3 and FlexProp_5.3.0-beta.

[LocalVars_tests.zip](https://github.com/totalspectrum/flexprop/files/6168771/LocalVars_tests.zip)

**Comment by totalspectrum** [comment]
The Spin2 language specification says in the description of PUB and PRI blocks:

"Results are initialized to zero on method entry, while local variables are undefined."

So flexspin and PNut actually agree on this, it's just that in your particular program the undefined values in the local variables happened to be 0 for PNut -- but the compiler does not guarantee this.

I agree that a warning about using variables before initializing them would be useful, and there's an issue for that open in flexspin..
