### ISSUE TITLE
Compiling program always shows 0 bytes as length of compilation

### ISSUE THREAD

**Issue by Jaan-Doh** [totalspectrum/flexprop#42]
When compiling a program in FlexProp the compilation information window and the bottom of the screen always shows 0 bytes as the length of the compiled file...
(see attached jpg)

I just click Compile for P2 - I do not flash and there is no prop device connected (in case that is relevant

![compilesize](https://user-images.githubusercontent.com/21372759/112384179-fe7df880-8ce5-11eb-9343-65c1aec242f5.jpg)
).

**Comment by totalspectrum** [comment]
I'm not able to reproduce this. Does it happen for any program that you try to run, including the samples (like blink.spin2)? Is it possible that your disk is full? If you enable the listing file, does that show up OK?

**Comment by Jaan-Doh** [comment]
Hi Eric,

Thank you for taking time out to assess this issue...

After reading your message,
I retried compilation of my (unfinished) program...

And below are the results for your reference...


** SAMPLE #1 - BASIC FILE
**Main program compilation window text (THIS IS A .BAS File)**
**The compilation completes without any errors but program size is zero


"D:/MY_PROJECT/flexprop/flexprop/bin/flexspin" -2 -l -D_BAUD=230400 -O1   --fixedreal -I "D:/MY_PROJECT/flexprop/flexprop/include" -I "D:/JD_Fwk_1/ver1"  "D:/JD_Fwk_1/ver1/clsJD_Framework.bas"
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.2.0 Compiled on: Feb 27 2021
clsJD_Framework.bas
|-clsJD_Fwk_MailMan.spin2
|-clsJD_Arena.spin2
|-clsJD_CmdLine.spin2
|-clsJD_PrintLine.spin2
|-clsJD_Palette64.spin2
|-clsJD_Palette256.spin2
|-clsJD_Error.spin2
|-vgatext_640x480.spin2
|-|-vga_tile_driver.spin2
clsJD_Framework.bas
|-clsJD_Fwk_MailMan.spin2
|-clsJD_Arena.spin2
|-clsJD_CmdLine.spin2
|-clsJD_PrintLine.spin2
|-clsJD_Palette64.spin2
|-clsJD_Palette256.spin2
|-clsJD_Error.spin2
|-vgatext_640x480.spin2
|-|-vga_tile_driver.spin2
Done.
Program size is 0 bytes
Finished at Thu Mar 25 14:43:21 2021

'End of the section above ----------------------------------------------------


** SAMPLE #2 - SPIN FILE
**program compilation window text (THIS IS A .SPIN2 File)**
**The compilation completes without any errors and program size is visible


"D:/MY_PROJECT/flexprop/flexprop/bin/flexspin" -2 -l -D_BAUD=230400 -O1   --fixedreal -I "D:/MY_PROJECT/flexprop/flexprop/include" -I "D:/JD_Fwk_1/ver1"  "D:/JD_Fwk_1/ver1/vgatext_640x480.spin2"
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.2.0 Compiled on: Feb 27 2021
vgatext_640x480.spin2
|-vga_tile_driver.spin2
vgatext_640x480.p2asm
Done.
Program size is 9884 bytes
Finished at Thu Mar 25 14:44:03 2021

'End of the section above ----------------------------------------------------


** SAMPLE #3 - BASIC FILE
**program compilation window text (THIS IS A .BAS File)**
**The compilation completes without any errors but program size is zero


"D:/MY_PROJECT/flexprop/flexprop/bin/flexspin" -2 -l -D_BAUD=230400 -O1   --fixedreal -I "D:/MY_PROJECT/flexprop/flexprop/include" -I "D:/JD_Fwk_1/ver1"  "D:/JD_Fwk_1/ver1/clsJD_Fwk_Record_Subsystem.bas"
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.2.0 Compiled on: Feb 27 2021
clsJD_Fwk_Record_Subsystem.bas
clsJD_Fwk_Record_Subsystem.bas
Done.
Program size is 0 bytes
Finished at Thu Mar 25 14:48:21 2021

'End of the section above ----------------------------------------------------


** SAMPLE #4 - BASIC FILE
**program compilation window text (THIS IS A .BAS File)**
**The compilation completes without any errors but program size is zero


"D:/MY_PROJECT/flexprop/flexprop/bin/flexspin" -2 -l -D_BAUD=230400 -O1   --fixedreal -I "D:/MY_PROJECT/flexprop/flexprop/include" -I "D:/JD_Fwk_1/ver1"  "D:/JD_Fwk_1/ver1/clsJD_Fwk_WordFieldObject.bas"
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.2.0 Compiled on: Feb 27 2021
clsJD_Fwk_WordFieldObject.bas
clsJD_Fwk_WordFieldObject.bas
Done.
Program size is 0 bytes
Finished at Thu Mar 25 14:44:50 2021



From the above it appears to me that this issue is only happening with a basic file?
I have FlexProp extracted to a folder on my D: drive (Not primary drive)
One thing though, it is a CLASS file so would that make a difference?

I say this because it just a class not the actual program that uses the class...


I have attached a simple program file for you to try.



Regards,


Jaan Doh






________________________________

**Comment by totalspectrum** [comment]
I think I see the problem -- your program doesn't actually do anything. It declares the class, but never actually uses it, so the compiler is optimizing it away. In theory disabling optimization should fix this, but there are probably some cases where it won't. your best bet is to declare an instance of the class  and call a method in it. Do you have some kind of test framework you could try out?

**Comment by Jaan-Doh** [comment]
Thank You,

I will try that after I get back from work tomorrow evening.

Regards,

Jaan Doh



________________________________

**Comment by Jaan-Doh** [comment]
Hiya Eric,

Sorry for the delay in getting back to you.
Well I tried my program and the compiler still gave errors which I could not understand.

So to simplify things I created a new very simple program,
with a simple class, and another file (Program) to use the class.






#TEST NUMBER 1 - File #1
'---------------------------------------------
'-> [File] clsTestClass.Bas
'---------------------------------------------
'
Dim GlobalVar as Byte
'
Class clsTestClass
   '
   Sub Initialise(pNewGlobalVarValue)
      '
      Globalvar = pNewGlobalVarValue
      '
   End Sub
   '
End Class
'---------------------------------------------



#TEST NUMBER 1 - File #2
'---------------------------------------------
'-> [File] clsTestClassDemo.Bas
'---------------------------------------------
Dim MyTestClass as Class Using "clsTestClass.bas"

Sub Start
   '
   MyTestClass.Initialise(6)
   '
End Sub
'---------------------------------------------
And the result of compilation was...

"D:/MY_PROJECT/flexprop/flexprop/bin/flexspin" -2 -l -D_BAUD=230400 -O1   --fixedreal -I "D:/MY_PROJECT/flexprop/flexprop/include" -I "D:/JD_Fwk_1/ver1"  "D:/JD_Fwk_1/ver1/clsTestClassDemo.bas"
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.2.0 Compiled on: Feb 27 2021
clsTestClassDemo.bas
|-clsTestClass.bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: unknown identifier Initialise in class clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: Initialise is not a member of clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: unknown identifier Initialise in class clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: Initialise is not a member of clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: unknown identifier Initialise in class clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: Initialise is not a member of clsTestClass_bas






#TEST NUMBER 2
I was unsure if the location of the DIM GlobalVar statement was in the wrong place...
So I moved it INSIDE the class

#TEST NUMBER 2 - File #1
'---------------------------------------------
'-> [File] clsTestClass.Bas
'---------------------------------------------
Class clsTestClass
   '
   Dim GlobalVar as Byte
   '
   Sub Initialise(pNewGlobalVarValue)
      '
      Globalvar = pNewGlobalVarValue
      '
   End Sub
   '
End Class
'---------------------------------------------



#TEST NUMBER 2 - File #2
'---------------------------------------------
'-> [File] clsTestClassDemo.Bas
'---------------------------------------------
Dim MyTestClass as Class Using "clsTestClass.bas"

Sub Start
   '
   MyTestClass.Initialise(6)
   '
End Sub
'---------------------------------------------
And the result of second attempt at compilation was...

"D:/MY_PROJECT/flexprop/flexprop/bin/flexspin" -2 -l -D_BAUD=230400 -O1   --fixedreal -I "D:/MY_PROJECT/flexprop/flexprop/include" -I "D:/JD_Fwk_1/ver1"  "D:/JD_Fwk_1/ver1/clsTestClassDemo.bas"
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.2.0 Compiled on: Feb 27 2021
clsTestClassDemo.bas
|-clsTestClass.bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: unknown identifier Initialise in class clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: Initialise is not a member of clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: unknown identifier Initialise in class clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: Initialise is not a member of clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: unknown identifier Initialise in class clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:6: error: Initialise is not a member of clsTestClass_bas
child process exited abnormally
Finished at Sat Mar 27 12:01:48 2021



I wish I had more experience at micro-controller programming,
So I could pinpoint the issue, but I cannot seem to find the problem.

I understand that moving the DIM GlobalVar statement out of the top and into the class itself
changes it's scope from a global var to a local var (local to the class).

But either way it refuses to compile, I'm guessing it's my inexperience butI'm not sure.






#TEST NUMBER 3
I even tried to remove the Sub_Start() method and call the MyTestClass.Initialise(pNewValue) method directly rather than from inside a method
but even that failed.


#TEST NUMBER 3 - File #1
'---------------------------------------------
'-> [File] clsTestClass.Bas
'---------------------------------------------
Class clsTestClass
   '
   Dim GlobalVar as Byte
   '
   Sub Initialise(pNewGlobalVarValue)
      '
      Globalvar = pNewGlobalVarValue
      '
   End Sub
   '
End Class
'---------------------------------------------



#TEST NUMBER 3 - File #2
'---------------------------------------------
'-> [File] clsTestClassDemo.Bas
'---------------------------------------------
Dim MyTestClass as Class Using "clsTestClass.bas"

MyTestClass.Initialise(6)

'---------------------------------------------
With the following compilation feedback

"D:/MY_PROJECT/flexprop/flexprop/bin/flexspin" -2 -l -D_BAUD=230400 -O1   --fixedreal -I "D:/MY_PROJECT/flexprop/flexprop/include" -I "D:/JD_Fwk_1/ver1"  "D:/JD_Fwk_1/ver1/clsTestClassDemo.bas"
Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2021 Total Spectrum Software Inc.
Version 5.2.0 Compiled on: Feb 27 2021
clsTestClassDemo.bas
|-clsTestClass.bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:4: error: unknown identifier Initialise in class clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:4: error: Initialise is not a member of clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:4: error: unknown identifier Initialise in class clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:4: error: Initialise is not a member of clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:4: error: unknown identifier Initialise in class clsTestClass_bas
D:/JD_Fwk_1/ver1/clsTestClassDemo.bas:4: error: Initialise is not a member of clsTestClass_bas
child process exited abnormally
Finished at Sat Mar 27 12:11:20 2021


One thing which jumps out at me is that the compilation error messages seem to be repeating!
And the second to last line says "child process exited abnormally"

Finally, I want to apologise for taking up your time as I know how valuable time is.




Regards,

Jaan Doh






________________________________

**Comment by totalspectrum** [comment]
By using *both* "class using clsTestClass.bas" and "class" inside clsTestClass.bas, you're creating a strange class within a class that won't do what you expect. That is, "class using" already creates a class with the contents of the "using" file. If that file itself also has "class" in it, then that will create an "inner" class.

Just use one or the other. I think the easiest way to fix your problem is to remove the "class" and "end class" lines in clsTestClass.bas.

**Comment by Jaan-Doh** [comment]
Thank You,

I will do as you recommend...


Regards,

Jaan Doh


________________________________
