### ISSUE TITLE
flexprop not compiling with latest macOS (11.5.2) 2 errors compiling for flexprop.bin

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#44]
**After a git pull (and a complete git clone) of flexprop, I'm no longer able to build flexprop on latest macOS 11.5.2...**
**There seems to (yet again) be an issue around Tk versions.**

**The error starts here:**

> cc  -o flexprop.bin src/flexprop_native.c -I/opt/tcl-tk/include -L/opt/tcl-tk/lib -ltk8.6 -ltcl8.6 -lz -lpthread -framework CoreFoundation -framework CoreServices -framework Cocoa -framework Carbon -framework IOKit -lm -lobjc
> In file included from src/flexprop_native.c:23:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/tk.h:31:3: error: Tk 8.5 must be compiled with tcl.h from Tcl 8.5
> ##error Tk 8.5 must be compiled with tcl.h from Tcl 8.5
>         ^
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/tk.h:86:11: fatal error: 'X11/Xlib.h' file not found
> ##include <X11/Xlib.h>
>                 ^~~~~~~~~~~~
> 2 errors generated.
> make: *** [flexprop.bin] Error 1

**Comment by dgately** [comment]
A possible solution...

The flexprop Makefile includes:
=====
ifeq ($(OS),macosx)
NATIVETK_INC =**-I/opt/tcl-tk/include**
NATIVETK_LIBS=**-L/opt/tcl-tk/lib** -ltk8.6 -ltcl8.6 -lz -lpthread -framework CoreFoundation -framework CoreServices -framework Cocoa -framework C$
endif
=====
But, macOS (at least 101.5.2) has no tcl-tk directory at /opt... That directory appears in /usr/local/opt  This is possibly a home-brew issue if not a macOS default. I'm not sure because I have home-brew and Tcl Tk installed.

Here's the change I made to fix the build problem
=====
ifeq ($(OS),macosx)
NATIVETK_INC =-I/usr/local/opt/tcl-tk/include
NATIVETK_LIBS=-L/usr/local/opt/tcl-tk/lib -ltk8.6 -ltcl8.6 -lz -lpthread -framework CoreFoundation -framework CoreServices -framework Cocoa -framework C$
endif
=====

I fixed the X11 not found directory as well with the following change to my file system:
=====
ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/X11 /usr/local/include/X11
=====
This put a soft link in /usr/local/include/ from the XCode Framework's X11

**Comment by totalspectrum** [comment]
Thanks for the bug reports. I think it should be fixed now, and will build correctly with the tcl-tk installed with homebrew.
