### ISSUE TITLE
Floating point printing

### ISSUE THREAD

**Issue by cewick70** [totalspectrum/flexprop#45]
Appears to be a problem with floating point printf and sprintf with 5.9.2 "C" compiler.  Program written under previous editions worked fine, but under 5.9.2 all floating point formated entries (ex: %6.1f) just prints ???.  ex: this program uses sprintf  and prints floats fine in previous 5.5.2.

**Comment by totalspectrum** [comment]
Thanks for the bug report! This is fixed in github now. A work around is to define the symbol INCLUDE_FLOATS, that is to add -DINCLUDE_FLOATS=1 on the command line.
