### ISSUE TITLE
flexprop terminal output reports exec error on ctrl-] or ctrl-Z 

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#47]
flexprop version: 5.9.4-beta...

terminating terminal mode on macOS results in an exec error message... Appears to expect flexprop.mac as an application!

> $ /Users/altergator/flexprop//bin/loadp2 -p /dev/cu.usbserial-A601RZ6G -b230400 /Users/altergator/Documents/P2ESCode/CALLD-Example/calld.binary -9/Users/altergator/Documents/P2ESCode/CALLD-Example -k -T -SINGLE; osascript -e 'tell application "flexprop.mac" to activate'; exit 0
> ( Entering terminal mode.  Press Ctrl-] or Ctrl-Z to exit. )
> **35:43: execution error: Can’t get application "flexprop.mac". (-1728)**
> Saving session...completed.

**Comment by totalspectrum** [comment]
Thanks for the bug report! I manually renamed flexprop to flexprop.mac for the .zip file distribution, but didn't do this for "make install". Actually there's no need to use the .mac suffix, so I've fixed the scripts to use just "flexprop".
