### ISSUE TITLE
flexprop version 5.9.4 doesn't load to P2 Edge on macOS without "-SINGLE" option

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#48]
When trying to load any compiled binary during "Compile & Run on P2", a timeout error returns unless the "-SINGLE" option is added to the Run Command line in Configure Commands panel... This happens on .bas and .spin2 compile/run attempts. 

> $ /Users/altergator/flexprop//bin/loadp2 -p /dev/cu.usbserial-A601RZ6G -b230400 /Users/altergator/Desktop/rayTest.binary -9/Users/altergator/Desktop -k -T; osascript -e 'tell application "flexprop.mac" to activate'; exit 0
> **ERROR: timeout waiting for initial checksum: got -1
> Try increasing the FIFO setting if not large enough for your setup**
> Press enter to continue...

Attempt with "-SINGLE" option:

> $ /Users/altergator/flexprop//bin/loadp2 -p /dev/cu.usbserial-A601RZ6G -b230400 /Users/altergator/Desktop/rayTest.binary -9/Users/altergator/Desktop -k -T -SINGLE; osascript -e 'tell application "flexprop.mac" to activate'; exit 0
> ( Entering terminal mode.  Press Ctrl-] or Ctrl-Z to exit. )

**Comment by totalspectrum** [comment]
Thanks for the bug report. I don't have a P2 Edge to test with, unfortunately. Do you happen to know how large of a FIFO is required to make loadp2 work?

**Comment by totalspectrum** [comment]
I'll change the default to 1024. Thanks for checking this!
