### ISSUE TITLE
on macOS 12.0.1 can no longer open or save files from flexprop editor

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#49]
After updating to the latest macOS (12.0.1) and newest flexprop 5.9.4, the flexprop editor no longer allows file access. Trying to open files or save them results in "The open file operation failed" dialog box. And, an Assertion failure appears in the Terminal where flexprop was launched. Not sure if the mac update or flexprop version are causing the issue. Could be a Tcl issue with macOS 12.0.1... A copy of the console error message and a screenshot follow:

`$ ./flexprop
2021-10-30 06:27:38.320 flexprop[8795:1239752] *** Assertion failure in -[NSOpenPanel beginServicePanel:asyncExHandler:], NSVBOpenAndSavePanels.m:1907
2021-10-30 06:27:38.326 flexprop[8795:1239752] -[NSSavePanel beginWithCompletionHandler:]_block_invoke caught non-fatal NSInternalInconsistencyException '<NSOpenPanel: 0x7f7fd771c000> is attempting to advance this Open/Save panel to run phase while another self.advanceToRunPhaseCompletionHandler is in waiting for a previous attempt. An Open/Save panel cannot start to advance more than once.' with user dictionary {
    NSAssertFile = "NSVBOpenAndSavePanels.m";
    NSAssertLine = 1907;
} and backtrace (
	0   CoreFoundation                      0x00007ff819185e5b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff818ee6b9d objc_exception_throw + 48
	2   Foundation                          0x00007ff81a03c653 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 267
	3   AppKit                              0x00007ff81c53f269 -[NSSavePanel beginServicePanel:asyncExHandler:] + 475
	4   AppKit                              0x00007ff81c54051d -[NSSavePanel runModal] + 297
	5   libtk8.6.dylib                      0x00000001052fff53 showOpenSavePanel + 171
	6   libtk8.6.dylib                      0x00000001052ff843 Tk_GetOpenFileObjCmd + 2001
	7   libtcl8.6.dylib                     0x00000001053bc9f4 TclNRRunCallbacks + 79
	8   libtk8.6.dylib                      0x000000010528d547 TkInvokeMenu + 488
	9   libtk8.6.dylib                      0x000000010530c652 -[TKMenu(TKMenuActions) tkMenuItemInvoke:] + 150
	10  AppKit                              0x00007ff81bd3864d -[NSApplication(NSResponder) sendAction:to:from:] + 288
	11  AppKit                              0x00007ff81be2d9de -[NSMenuItem _corePerformAction] + 413
	12  AppKit                              0x00007ff81be2d6fe -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 95
	13  AppKit                              0x00007ff81be78519 -[NSMenu performActionForItemAtIndex:] + 113
	14  AppKit                              0x00007ff81be7849f -[NSMenu _internalPerformActionForItemAtIndex:] + 82
	15  AppKit                              0x00007ff81be782e8 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 101
	16  AppKit                              0x00007ff81be11eb3 NSSLMMenuEventHandler + 1078
	17  HIToolbox                           0x00007ff821cffbad _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1391
	18  HIToolbox                           0x00007ff821cfefde _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 333
	19  HIToolbox                           0x00007ff821d13e0b SendEventToEventTarget + 39
	20  HIToolbox                           0x00007ff821d742ef _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 365
	21  HIToolbox                           0x00007ff821d9975e SendMenuCommandWithContextAndModifiers + 46
	22  HIToolbox                           0x00007ff821d99708 SendMenuItemSelectedEvent + 348
	23  HIToolbox                           0x00007ff821d9955a _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	24  HIToolbox                           0x00007ff821d99f60 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 631
	25  HIToolbox                           0x00007ff821d99c51 _HandleMenuSelection2 + 459
	26  AppKit                              0x00007ff81bcd2b79 _NSHandleCarbonMenuEvent + 215
	27  AppKit                              0x00007ff81bcd29e6 _DPSEventHandledByCarbon + 54
	28  AppKit                              0x00007ff81bb32750 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3447
	29  libtk8.6.dylib                      0x0000000105311f05 TkMacOSXEventsCheckProc + 329
	30  libtcl8.6.dylib                     0x0000000105464ed0 Tcl_DoOneEvent + 302
	31  libtk8.6.dylib                      0x0000000105262bc5 Tk_MainLoop + 33
	32  libtk8.6.dylib                      0x000000010526f7d2 Tk_MainEx + 1624
	33  flexprop                            0x0000000104fdca5e main + 94
	34  dyld                                0x000000010b69e4fe start + 462
)`
![flexzprop_Files_Issue](https://user-images.githubusercontent.com/3009364/139534742-6e9d74c4-dff7-4305-bacf-7217fceaa0c9.jpg)

**Comment by dgately** [comment]
Looks like this issue has been known for a while: https://bugs.python.org/issue44828... Though, appears to be an issue with Tk and not Python, where the issue was reported.

**Comment by totalspectrum** [comment]
Looks like we'll need an updated version of Tk :(. Thanks for looking into this.

**Comment by totalspectrum** [comment]
This seems to be fixed with tcl-tk version 8.6.12, which is now available in homebrew. I've added Mac binaries back to the .zip file. Thanks for the bug report!
