### ISSUE TITLE
Building flexprop on Raspberry Pi requires pandoc and lyx

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#50]
When building flexprop on a recent (bullseye) release of Raspberry Pi OS, the HTML help files will not be created unless additional resources are available. The docs process to create the .html help files requires pandoc as well as LaTeX (or a replacement, such as lyx). 

After an initial build with "make install", on Raspberry Pi, flexprop's GUI cannot find the .html help files for spin, BASIC, C, etc... Reviewing the Makefile displays the requirement of 'pandoc' to build pdf and html files from the .md help files. Installing pandoc (with sudo apt install pandoc) helps to get a bit further, creating pdfs but some form of LaTeX is needed to create the .html files. Not finding a simple install for LaTeX, I did find that 'lyx' can be installed (sudo apt install lyx) and this allows the build/Install to complete successfully.

Perhaps just an update to the readme will help other Raspberry Pi users!

**Comment by totalspectrum** [comment]
Thank you for the suggestion! I've updated the README to include a description of the documentation prerequisites.
