### ISSUE TITLE
src/version.tcl not part of make clean and not always updated correctly

### ISSUE THREAD

**Issue by amock** [totalspectrum/flexprop#51]
I ran `make install` without installing all of the dependencies and `src/version.tcl` ended up empty, which caused flexprop to fail with `Error in startup script: can't read "spin2gui_version": no such variable`.  To fix this I installed the missing package and then ran `make clean` and then `make install` again but since `src/version.tcl` wasn't removed make thought it was still up to date and didn't try to regenerate it.  Deleting `src/version.tcl` and running `make install` with the proper dependencies installed worked.

**Comment by totalspectrum** [comment]
Thanks for catching this, I've updated the Makefile.
