### ISSUE TITLE
Help files not accessible from within the editor

### ISSUE THREAD

**Issue by knivd** [totalspectrum/flexprop#52]
In the Help menu, the items "General compiler documentation", "BASIC Language", "C Language", and "Spin Language" cannon open the documentation, but instead result in an error. One here showing the error for C, the others are same with just the file name changing relevant to the option.

![Screenshot 2021-11-15 203412](https://user-images.githubusercontent.com/6014528/141850537-bb58601c-dafc-48ed-9da0-9a5534343bc4.png)

**Comment by totalspectrum** [comment]
Is there in fact a file K:/Others/APplications/flexprop/doc/c.html? There should be (it's in the standard .zip file). If so, then the problem is that for some reason you have no web browser configured to read .html files. I'm not quite sure how this is done in Windows, but probably double clicking on any html file will offer you the choice of setting up the web browser you would like to use.

**Comment by knivd** [comment]
Yes, all the documents are in their folders. From what I see, the problem is due to the duplicated '/' character in the path when flexprop attempts to access the file

**Comment by totalspectrum** [comment]
Ah... it looks like some browsers don't like the extra /. You can get rid of this by changing the file flexprop.tcl in the src directory to change "[string length $ROOTDIR]-4" to "[string length $ROOTDIR]-5":
```
diff --git a/src/flexprop.tcl b/src/flexprop.tcl
index a264837..be846dc 100755
--- a/src/flexprop.tcl
+++ b/src/flexprop.tcl
@@ -10,7 +10,7 @@
 variable myScript [file normalize [info script]]
 variable ROOTDIR [file dirname $myScript]
 if { [file tail $ROOTDIR] eq "src" } {
-    set ROOTDIR [string range $ROOTDIR 0 [string length $ROOTDIR]-4]
+    set ROOTDIR [string range $ROOTDIR 0 [string length $ROOTDIR]-5]
 }
 package require Tk
 #package require autoscroll
```

**Comment by knivd** [comment]
Works fine after the patch. Thanks
