### ISSUE TITLE
After uploading, running and quitting a binary via PropLoader (WiFi), proploader's process appears to stick around

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#53]
on macOS...

After compiling, uploading, running P2 binaries, via PropLoader/WiFi, when I quit the terminal (Control-]), I noticed that a proploader process is still running. In fact, all previous proploader processes are still running. This showed up as my MacBook Pro fan running hard. I used macOS's Activity Monitor to see about 6 proploader processes taking up quite a lot of my CPU time. I had to force-quit the processes to get my fan to spin-down.

I noticed that this was during use of flexprop's new internal terminal option!

Is there a possibility that proploader processes are not being unloaded at the end of a terminal session.

**Comment by totalspectrum** [comment]
That's odd, I thought I had fixed that bug. Is that with the currently checked in sources, or the posted flexprop5.9.7-beta.zip?

**Comment by dgately** [comment]
Yes, with 5.9.7 beta!

**Comment by totalspectrum** [comment]
I do see a zombie proploader process sometimes, but I haven't seen more than 1 non-zombie at a time, on Mac or Linux.

(1) When you use Control-] to quit the terminal, does the terminal window close?
(2) Does the same behavior (proploader processes hanging around) happen if you use Control-Z and/or close the window manually?
(3) Does your proploader version start with:
PropLoader (totalspectrum branch) v1.0-90 (2022-01-14 08:06:50 g5154a15)

**Comment by dgately** [comment]
(1) Control-] causes the terminal window to close
(2) Control-Z same as Control-]
(3) Yes, version is the same as: (totalspectrum branch) v1.0-90 (2022-01-14 08:06:50 g5154a15)
When Control-] or -Z is used, there is an empty-ish process that is left, but appears to not being doing anything:

Greping ps aux & looking for "proploader" gives me:
```
% ps aux | grep proploader
altergator       29178   0.0  0.0 34253900    936 s002  S+    6:49PM   0:00.00 grep --color=auto proploader
altergator       29104   0.0  0.0        0      0 s000  Z+    6:47PM   0:00.00 (proploader)     **<== process still exists but is not doing anything** 
```
**The case where I initially reported the issue may be that I had leftover proploader processes running before a git pull and rebuild of flexprop. I had not restarted my MacBook Pro in days, so maybe those processes were from the prior flexprop... Those proploader processes were definitely chewing up the CPU.**

So, maybe just close this and I'll keep watching for errant processes! Thx!

**Comment by dgately** [comment]
Here's a pesky update!

I can force a proploader process to stay in execution and take up CPU resources... If you don't use Control-] or -Z, and instead click the internal terminal window close box, a proploader process will stay in execution. Even after you quit flexprop! Is it possible to end the proploader process in this sitiuation? Anyway, you can still close if this is considered a non-issue.

**Comment by totalspectrum** [comment]
I think this has been fixed for a while, hasn't it? If not, please re-open.
