### ISSUE TITLE
Flexprop 5.9.10 Firewall Alert concerning proploader.exe

### ISSUE THREAD

**Issue by francisbauer** [totalspectrum/flexprop#56]
I just unpacked Flexprop 5.9.10 and got the Norton Firewall alert below when launching _flexprop.exe_, it concerns _proploader.exe_ wanting to access UDP port#32420.

Is this expected?  I don't get that alert when running 5.9.9 or earlier versions.

I don't know if I should over-ride the recommendation to block the transaction.  The alert shows up immediately after starting flexprop, and I haven't even loaded any code or connected a propeller.
After I let Norton block the transaction, I can still load some spin2 code and have it download/run the code on a P2 Edge board.  So I don't know what the UDP transaction's purpose is/was...
 
![FirewallAlert](https://user-images.githubusercontent.com/53076503/165222335-4c58a804-be7f-4cfc-8469-b4403ca658b8.jpg)

**Comment by totalspectrum** [comment]
That's normal... it's flexprop scanning the network for propeller WiFi cards. Flexprop 5.9.9 did it as well; I'm not sure why Norton wouldn't have complained then. If you don't have any WiFi cards then it's fine to block the network transaction, but it's also OK to let it go through.
