### ISSUE TITLE
"flexprop5.9.10.zip is not commonly downloaded and may be dangerous" in Chrome for Windows

### ISSUE THREAD

**Issue by jacgoudsmit** [totalspectrum/flexprop#57]
When I clicked on the ZIP file on the Release 5.9.10 page, Chrome for Windows showed an error message "flexprop5.9.10.zip is not commonly downloaded and may be dangerous". I had to click the "Keep" option in the popup button to make it download the zip file (which I then proceeded to use for building the installer, as I always do when there's a new release).

I don't know if this is just a problem on my PC, and I don't know if this has anything to do with the firewall issue that was reported earlier this week. but I thought I'd mention it.

If I'm not mistaken, Chrome doesn't normally show the "Keep" button. The default setting is to deny the download; you have to make a change to the Chrome security and privacy settings to allow it show the override button.

The picture shows the bottom corner of the Chrome browser window. It changed the file name when I took the screenshot, because I already had it downloaded before.
<img width="208" alt="flexprop" src="https://user-images.githubusercontent.com/1652770/165579702-53317605-d603-4b71-ac39-da4ba423d0cb.png">

===Jac

**Comment by totalspectrum** [comment]
Thank you for reporting this. There's really not much I can do about it, and Google is no help at all. The executable is signed, and virus-total agrees that there are no viruses in the .zip (not surprising, I built it myself from source on a Linux machine, which is highly unlikely indeed to be infected with a Windows virus).
