### ISSUE TITLE
Can't seem to build for Fedora 36

### ISSUE THREAD

**Issue by cbmeeks** [totalspectrum/flexprop#59]
I have installed (I think) all of the needed dev libraries but when I try to install on my Fedora 36 installation, I get errors.  Such as:

    if test -f /home/cbmeeks/flexprop/Makefile; then echo "ERROR: Install directory contains a Makefile (possibly installing to original source)"; exit 1; fi
    (make -C board/sdcard P2CC="`pwd`/bin/flexspin -2 -I`pwd`/spin2cpp/include")
    make[1]: Entering directory '/home/cbmeeks/tmp/flexprop/board/sdcard'
    /home/cbmeeks/tmp/flexprop/bin/flexspin -2 -I/home/cbmeeks/tmp/flexprop/spin2cpp/include -o sdboot.binary sdboot.c ff.c sdmm.c
    Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2022 Total Spectrum Software Inc.
    Version 5.9.18-HEAD-v5.9.18 Compiled on: Oct 28 2022
    sdboot.c
    ff.c
    sdmm.c
    posixio.c
    fputs.c
    fmt.c
    errno.c
    sdboot.p2asm
    Done.
    Program size is 25704 bytes
    make[1]: Leaving directory '/home/cbmeeks/tmp/flexprop/board/sdcard'
    rm -f board/sdcard/*.p2asm
    mv board/sdcard/sdboot.binary board/P2ES_sdcard.bin
    mkdir -p flexprop/bin
    mkdir -p flexprop/doc
    mkdir -p flexprop/board
    cp -r README.md License.txt samples src flexprop
    cp -r spin2cpp/doc/* flexprop/doc
    cp -r spin2cpp/Changelog.txt flexprop/doc/Changelog-compiler.txt
    cp -r Changelog.txt flexprop/doc/Changelog-gui.txt
    cp -r loadp2/README.md flexprop/doc/loadp2.md
    cp -r loadp2/LICENSE flexprop/doc/loadp2.LICENSE.txt
    cp -r spin2cpp/COPYING.LIB flexprop/doc/COPYING.LIB
    cp -r spin2cpp/include flexprop/
    cp -r doc/*.txt flexprop/doc
    cp -r board/* flexprop/board
    cc  -o flexprop.bin src/flexprop_native.c src/p2debug.c -I/usr/include/tcl8.6 -ltk8.6 -ltcl8.6 -lfontconfig -lXft -lXss -lXext -lX11 -lz -ldl -lpthread -lm
    /usr/bin/ld: cannot find -lXss
    collect2: error: ld returned 1 exit status
    make: *** [Makefile:135: flexprop.bin] Error 1

I'm not sure where to go from here.  Any ideas on what I could try next?

Thanks

**Comment by totalspectrum** [comment]
Sorry for the delay getting back to you, for some reason I missed this bug report.

`-lXss` is found in libXScrnSaver-devel on Fedora. I've updated the build instructions to describe what to install on Fedora 36, and verified that it works in a fresh virtual machine.
