### ISSUE TITLE
flexprop make failing with latest sources

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#60]
On both a macOS system as well as a RasperryPi 4, I get the same error when running "make install" with latest flexprop sources:

On both systems "git pull" had been exec'd, to gather all new sources...

on macOS:

> cd spin/; /Users/altergator/source/flexprop/bin/flexspin -o /Users/altergator/source/flexprop/proploader-macosx-build/obj/sd_helper.binary sd_helper.spin
> Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2022 Total Spectrum Software Inc.
> Version 5.9.20-beta-v5.9.19-46-gb2d58e0f Compiled on: Nov 20 2022
> sd_helper.spin
> |-packet_driver.spin
> |-fsrw.spin
> |-|-safe_spi_c3.spin
> /Users/altergator/source/flexprop/PropLoader/spin/fsrw.spin:79: error: Unable to determine size of array
> /Users/altergator/source/flexprop/PropLoader/spin/fsrw.spin:79: error: Unable to determine size of array
> /Users/altergator/source/flexprop/PropLoader/spin/packet_driver.spin:40: error: Unable to determine size of array
> /Users/altergator/source/flexprop/PropLoader/spin/packet_driver.spin:40: error: Unable to determine size of array
> make[1]: *** [/Users/altergator/source/flexprop/proploader-macosx-build/obj/sd_helper.binary] Error 1
> make: *** [proploader-macosx-build/bin/proploader] Error 2

on RaspberryPi 4:

> cd spin/; /home/pi/source/flexprop/bin/flexspin -o /home/pi/source/flexprop/proploader-linux-build/obj/sd_helper.binary sd_helper.spin
> Propeller Spin/PASM Compiler 'FlexSpin' (c) 2011-2022 Total Spectrum Software Inc.
> Version 5.9.20-beta-v5.9.19-46-gb2d58e0f Compiled on: Nov 20 2022
> sd_helper.spin
> |-packet_driver.spin
> |-fsrw.spin
> |-|-safe_spi_c3.spin
> /home/pi/source/flexprop/PropLoader/spin/fsrw.spin:79: error: Unable to determine size of array
> /home/pi/source/flexprop/PropLoader/spin/fsrw.spin:79: error: Unable to determine size of array
> /home/pi/source/flexprop/PropLoader/spin/packet_driver.spin:40: error: Unable to determine size of array
> /home/pi/source/flexprop/PropLoader/spin/packet_driver.spin:40: error: Unable to determine size of array
> make[1]: *** [Makefile:152: /home/pi/source/flexprop/proploader-linux-build/obj/sd_helper.binary] Error 1
> make[1]: Leaving directory '/home/pi/source/flexprop/PropLoader'
> make: *** [Makefile:226: proploader-linux-build/bin/proploader] Error 2

**Comment by totalspectrum** [comment]
Thanks, that should be fixed now.
