### ISSUE TITLE
Spin2 QSIN and POLXY (CORDIC?) results

### ISSUE THREAD

**Issue by jrullan** [totalspectrum/flexprop#66]
Hi, I discovered this behavior using Qsin in a code that simulates a sinusoidal waveform:
```
CON
  _clkfreq = 200_000_000

PUB main()|i, sine_val
  repeat i from 0 to 100 step 10
    sine_val := Qsin(50,i,50)+ 50
    debug(udec(i), udec(sine_val))
    waitms(500)
```

In PropTool this is the result:
![image](https://user-images.githubusercontent.com/6475312/209143684-3c7f9369-613d-440c-90e1-7d1ca3473447.png)

In FlexProp values after d=50 stay at 50, this is the result:
![image](https://user-images.githubusercontent.com/6475312/209143840-ed56b4b5-c7d5-42e5-841c-48a84e8372bd.png)

**Comment by jrullan** [comment]
I did some experimentation with this method,

```
PUB pol_to_xy(l,angle):x,y
  angle := angle * DEGREE
  ORG
    QROTATE l, angle
    GETQX x
    GETQY y
  END
```
It gives the same result as with POLXY.

**Comment by totalspectrum** [comment]
The polxy problem is a different one from the qsin one, it is because in FlexProp $8000_0000 is treated as unsigned (internally FlexProp uses 64 bit integers, so this matters). I will try to fix this in the next release.

**Comment by totalspectrum** [comment]
I think both of the problems should be fixed now. Thanks for the bug reports!
