### ISSUE TITLE
Code doesn't run same as when compiled with PNut or Propeller Tool

### ISSUE THREAD

**Issue by ironsheep** [totalspectrum/flexprop#67]
[cjmj_pin_test_w_led_matrix.spin2.zip](https://github.com/totalspectrum/flexprop/files/10273651/cjmj_pin_test_w_led_matrix.spin2.zip)

I connected the eval LED MATRIX 8x7 board to P0-P7.

I build and run this simple file.

It should flash the Right edge column of the LEDs
then the column left of it, 
and then one more left of that
lastly, it should flash all LEDs.

Instead when compiled with v5.9.21 on Mac/RPi or Windows it simply
flashes the top and bottom LEDs of the right most column.

Does this help you find the problem?

**Comment by totalspectrum** [comment]
Thanks for the bug report. I think I can see what's wrong (the foo.[n] syntax is only extracting 1 bit in flexspin, but in PNut it can take multiple bits depending on the upper bits of n).

**Comment by totalspectrum** [comment]
This is fixed in the github source code now.
