### ISSUE TITLE
Spin2 method variables within repeat loop (after quit)

### ISSUE THREAD

**Issue by jrullan** [totalspectrum/flexprop#68]
This issue is related to the value of i after the repeat loop is broken.

Variable **i** should keep the last value assigned within the method but on quit it is taking the last value of the repeat loop, as if the loop keeps counting even when it is actually skipping the rest of the instructions within the loop.

```
CON
  _clkfreq = 200_000_000

PUB main()|i,values[8]

  repeat i from 0 to 7
    values[i] := i


  repeat i from 0 to 7
    if i == 5
      quit
    debug(sdec(i))

  debug(sdec(i), " <- should be 5")
```

In FlexProp...
![image](https://user-images.githubusercontent.com/6475312/209473915-7c2845f7-1bdb-48d1-98b6-78603875219e.png)

In Prop Tool...
![image](https://user-images.githubusercontent.com/6475312/209473940-afe79373-8892-413e-a773-6f2c2fbcd063.png)

**Comment by totalspectrum** [comment]
Thanks, this should be fixed now in 5.9.23.
