### ISSUE TITLE
flexprop build errors on MacOSX (latest SDK-Ventura 13.3 (22E252)) when building flexprop 6.05

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#69]
Unable to completely build flexprop on latest MacOSX Sdk. Note: spin2cpp builds, proploader builds, loadp2 builds, but building at root level, fails with "error: no member named 'nullptr_t' in the global namespace" error listed as well as further errors for the use of the nullptr_t variable... (20 errors total)

Possibly a MacOSX 13.3 SDK issue, but I was able to build several OSX projects in XCode with the new SDK, without issue. Note: After the latest MacOSX software update to Ventura 13.3, the Mac's automatic update option gave a notification of the availibility of the latest SDK that corresponds with 13.3 (as an XCode user & apple developer, these notifications follow most OS Software Updates!).

The last portion of the build process output (cut down from large original, but contains all errors):
[flexprop_65_MacOSX-SDK_Build_Errors.txt](https://github.com/totalspectrum/flexprop/files/11141446/flexprop_65_MacOSX-SDK_Build_Errors.txt)

**Comment by totalspectrum** [comment]
The errors are all in latform header files, so this definitely does look like an SDK problem.

**Comment by totalspectrum** [comment]
Also: from the log it looks like the errors are in proploader. Are you sure that built correctly?

**Comment by dgately** [comment]
Ah, you are correct! PropLoader does fail and all of the errors are within that part of the project! I've spent a lot of research time, looking for anyone else reporting this error against macOS Ventura. But there has been no Ventura-based claims or response from Apple. I do see this error reported in the past against older versions of macOS SDKs. I will report this in the Apple Developer Feedback app and see what transpires...

**Comment by totalspectrum** [comment]
I've added a #include <cstddef> to the top of PropLoader/src/main.cpp in the most recent release. Does that help?

**Comment by totalspectrum** [comment]
Thanks for looking into this! My Mac mini is too old to run Ventura, so I'm kind of behind on SDKs.

**Comment by dgately** [comment]
I have an older iMac that's running an old system (10.4?)... Trying to use that to build flexprop, but it's telling me that it can't find Xlib.h, which is clearly within $PATH. I'll just use your pre-built flexprop for now. Maybe apple will come through with a fix.
