### ISSUE TITLE
Segmentation violation with method pointers returning 9 values

### ISSUE THREAD

**Issue by jrullan** [totalspectrum/flexprop#75]
@totalspectrum 

I am having a segmentation violation when I try to compile this. I tested it with Propeller Tool and Spin Tools and they both work.

![image](https://github.com/totalspectrum/flexprop/assets/6475312/9641c145-2da1-4293-9a83-88593db1a4bd)

The child object is:

![image](https://github.com/totalspectrum/flexprop/assets/6475312/93db77e6-7c71-4783-bf11-53cea4fd7f7c)

The violation is caused by the call to `set_9_pointers`. 
My guess is that the call to the child `get_9_pointers` is causing the problem.
With 8 or less return values it compiles ok, but with 9 it hangs.

![image](https://github.com/totalspectrum/flexprop/assets/6475312/4973f53d-a3dc-4f95-9364-3f603627cebf)

Main_Object code:
```
CON
        _clkfreq = 200_000_000

OBJ
        my_child : "Child_object"

VAR
        LONG my_method_a, my_method_b, my_method_c, my_method_d, my_method_e, my_method_f, my_method_g, my_method_h, my_method_i


PUB main()
	set_8_pointers(@my_child.get_8_pointers)'<---- This works
	set_9_pointers(@my_child.get_9_pointers)'<---- This creates a segmentation violation

PUB set_8_pointers(method_ptr)|a,b,c,d,e,f,g,h
	a,b,c,d,e,f,g,h := method_ptr():8

PUB set_9_pointers(method_ptr)|a,b,c,d,e,f,g,h,i
	a,b,c,d,e,f,g,h,i := method_ptr():9
```

Child object code:
```
CON

PUB method_a()

PUB method_b()

PUB method_c()

PUB method_d()

PUB method_e()

PUB method_f()

PUB method_g()

PUB method_h()

PUB method_i()

PUB get_8_pointers(): a, b, c, d, e, f, g, h
{
        a := @method_a
        b := @method_b
        c := @method_c
        d := @method_d
        e := @method_e
        f := @method_f
        g := @method_g
        h := @method_h
}

PUB get_9_pointers(): a, b, c, d, e, f, g, h, i
{
        a := @method_a
        b := @method_b
        c := @method_c
        d := @method_d
        e := @method_e
        f := @method_f
        g := @method_g
        h := @method_h
        i := @method_i
}
```

**Comment by totalspectrum** [comment]
Thank you for the bug report. This is fixed in 6.1.8.
