### ISSUE TITLE
error: Inline assembly too large to fit in fcache when compiling P2-HUB75 demo project on Apple Silicon Mac

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#76]
After setting up a new Apple Silicon Mac with flexprop, for some projects (Stephen M Moraco's P2-HUB75 demos), I'm getting errors concerning FCACHE space & FCACHE being disabled.

 _Note: My old Mac is broken, so I am not able to retry on that Intel CPU Mac_

flexprop version: 6.1.9-beta
macOS version: Ventura 13.4.1

Attached: flexprop error log & a ZIP'd copy of the project...

Compile errors:
```
/Users/myuser/source/P2-HUB75-LED-Matrix-Driver/driver/isp_hub75_panel.spin2:160: warning: FCACHE is disabled, asm will be in HUB
/Users/myuser/source/P2-HUB75-LED-Matrix-Driver/driver/isp_hub75_panel.spin2:383: warning: FCACHE is disabled, asm will be in HUB
/Users/myuser/source/P2-HUB75-LED-Matrix-Driver/driver/isp_hub75_rgb3bit.spin2:628: warning: FCACHE is disabled, asm will be in HUB
/Users/myuser/source/P2-HUB75-LED-Matrix-Driver/driver/isp_hub75_rgb3bit.spin2:628: error: Inline assembly too large to fit in fcache
```

[FCACHE_error.txt](https://github.com/totalspectrum/flexprop/files/11936744/FCACHE_error.txt)

[demo_hub75_multiPanel-2023-07-03.zip](https://github.com/totalspectrum/flexprop/files/11936753/demo_hub75_multiPanel-2023-07-03.zip)

**Comment by Wuerfel21** [comment]
Enable optimizations.

**Comment by dgately** [comment]
Arg! It's always something simple... I must have turned optimizations off for another project. That's what happens when you're on vacation for a month and try to restart what you were working on before... Thx!

**Comment by Wuerfel21** [comment]
To be fair, inline asm going bad at O0 is a silly landmine
