### ISSUE TITLE
FLEXPROP version 6.2.1 disturbs Delta-Sigma ADC operations

### ISSUE THREAD

**Issue by GitDave99** [totalspectrum/flexprop#78]
Hi Eric, unfortunately the latest revision has disturbed ADC operations... the symptom is a large amount of random noise from 0 to about 60 out of 255, 8-bit mode of the ADC.

That's using the same code you have in hand. You would need to run the code on a P2 to see it.

Attached are before and after pix, the good one is the code running in PropTool.
The bad one is same code running in FlexProp. I compiled this code earlier today using 6.1.8, the ADC worked well.
![Running in PropTool](https://github.com/totalspectrum/flexprop/assets/86808503/a7ca8446-4deb-42f9-a893-c7518e8ea138)
![Running 6 2 1 compilation](https://github.com/totalspectrum/flexprop/assets/86808503/1ba2f19f-500c-472e-9b5b-3e0c4506532d)

**Comment by totalspectrum** [comment]
Did you change compile flags between 6.1.8 and 6.2.0? For example, was one optimized and the other not? Because if I disable fcache (the source of the bug in 6.1.8) then the two compilers generate the same code, except that the WAITATN function is now implemented the same as the PropTool compiler does (as a POLLATN loop).

**Comment by GitDave99** [comment]
No change, optimized or not, the delta-sigma ADC function has the noise in
6.2.1 but not in 6.1.8

**Comment by GitDave99** [comment]
Hi, Eric

Tell me, is there a test or ? I may do to help your troubleshooting?

A hint for your end, if you have a P2 Edge at hand, you can run the code
with no external hardware. I use the excellent SerialPlot, available on
github.

Hook up a serial to USB gizmo to pin 8 and gnd. Also ground pin 16, an ADC
input pin in my code.

 Arrange SerialPlot for 2Mbps and 20k fixed frame using the default AA BB
frame header and one channel. You should see a zero signal, at gnd level
with minimal noise.

If you see the large ranfom-like noise I am seeing, congrats! You have a
place to start!

Let me know if I can help.

Dave

**Comment by GitDave99** [comment]
Just playing around, with DBUG instantiation commented out and the WAITATN
labeled "DBUG done" also commented out, I then tried various optimization
levels.

0,1,2... all mess with the ADC.
But full optimization?

It works just fine! There's a  smoking gun for you! Good luck and good
hunting

Dave

**Comment by GitDave99** [comment]
Hi Eric,

I made some careful measurements of the baseline noise level from the
Delta-Sigma ADC under various conditions:
1) from PropTool, noise level is 0~3 grads out of 256
2) from FlexProp, full optimization, noise level is 0~14 grads out of 256
3) from FlexProp, any other opto, noise level is 0~51 grads out of 256

Case 2) is marginally acceptable, but I'd vastly prefer the same noise
level as in PropTool

I'll dig a bit more as time goes on.

Hope this tightens your loop on the maverick!

Dave

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by GitDave99** [comment]
The noise seems to have a repetition rate of 71 to 83KHz, depending on
optimization  level.

Not really random in nature

**Comment by totalspectrum** [comment]
Dave: thanks for the information. Looking at the code, it seems that the ADC capture is performed in assembly in the D_S ADC 2.spin2 file. That's not something the compiler or optimizer touches, so I don't see how it could be affected by the flexspin version or optimization level. Only the Spin2 code in the top object is compiled.

I notice you're running at a very high clock speed (320 MHz). Does slowing this down to below 300 MHz help anything? Officially the P2 is only rated to 180 MHz, although in practice it seems to work fine past 250 MHz.

(My PropPlug has stopped working, so at the moment I'm not able to read data from pin 8... any reason you chose that instead of the usual pin 63/62 combo?)

**Comment by GitDave99** [comment]
Because that pin set is dedicated to programming.

Pin 8 to another RS232 to USB dongle means I don't  have to fool with wires
while using pin 8 and can freely program while viewing waveforms using
SerialPlot.

I run 320MHz for HDMI but mostly because I can!

Haven't tried slowing it.

I know! Pasm inna core!! Yet the correlation of noise and option selection
is clear. Got me!

What can we do?

**Comment by GitDave99** [comment]
Recall that 6.1.8 never did that to the ADC.

The problem arrived when I compiled with 6.2.1 (did I get the Rev right?).

Still using 6.2.1, still got the issue. Puzzling

Well, it's  always something! Sooner or later it's  gonna fall

**Comment by totalspectrum** [comment]
If you look at the listing file, the only difference in the compilation between 6.1.8 and 6.2.1 is that there are some busy waits in place of WAITATN. This will put more thermal stress on the chip. Of course it's also possible that the busy wait is wrong, but I've looked at the generated code and it seems straightforward:
```
--- old.p2asm   2023-07-14 09:42:02.782775823 -0300
+++ new.p2asm   2023-07-14 09:41:01.067554452 -0300
@@ -157,14 +157,19 @@
        test    arg02, #1 wc
        drvc    #60
        cogatn  #2
-       waitatn
+LR__0002
+       mov     result1, #0
+       pollatn wc
+       subx    result1, #0
+       cmp     result1, #0 wz
+ if_e  jmp     #LR__0002
        drvh    #60
        mov     arg01, #2
        call    #__system___waitms
```

**Comment by totalspectrum** [comment]
(The busy waits were to match what the Spin2 interpreter does.)

**Comment by GitDave99** [comment]
Hmmmm... in Spin, do as the Spinners do. In PASM, ...

Interesting...

**Comment by GitDave99** [comment]
I'm  beginning to think that some difference in the revisions I driving two
states at once on one or more transistors, internal logic or GPIO. I'll
check around to see if the 3.3V power for the ADC group of pins gets noisy
or not.

**Comment by GitDave99** [comment]
I can say with confidence it is not noise on the 3.3V for pin group
starting on 16.

What then?

**Comment by totalspectrum** [comment]
Have you tried running at a lower clock frequency? Also, have you tried other pin groups? Right now I strongly suspect hardware problems due to overheating. I don't think the P2 Edge is reliable at 320 MHz, although it might be worth checking this on the forums.

**Comment by GitDave99** [comment]
Hi Eric! Good morning.

In my 50+ years of troubleshooting experience, I came up with two maxims.

1) the solution is simple, it's  just not obvious

2) it's  ALWAYS the last thing you did

In this case, the problem never existed until we changed from 6.1.8 to
6.2.1.

That's obvious!

So I suggest we go back to 6.1.8 and test.

Shall we?

**Comment by totalspectrum** [comment]
(1) I thought 6.1.8 only worked for you if optimization was disabled.

(2) If it's a bug in the compiler, then it's a bug in the code produced by the compiler. But 6.1.8 and 6.2.1 produce exactly the same code for your program when optimization is disabled, except that the waitatn() function is implemented by a pollatn() loop. I've double checked that loop and the logic is correctm but of course it'd be good to have another pair of eyes on it.

(3) If the logic of the loop is correct, then the only other differences are (a) a very slight difference in timing, and (b) a moderately large increase in the energy consumed by the COG while executing the loop (the WAITATN instruction stops the COG completely).

**Comment by GitDave99** [comment]
Yes, it worked with no optimization.

I want to test again with 6.1.8 regardless.

It's very clear, no problem with ADC noise, until 6.2.1

One can't argue with results!

How may I obtain it? That'll  teach me to archive past revisions!

**Comment by GitDave99** [comment]
Addressing the cog energy point.

That's why I measured the noise on the ADC group 3.3V regulator. The noise
is the same level for all test cases:

SPIN2 in PROPTOOL

Any option selection in FlexProp

Conclusion, not related to the symptom.

We'll get it, we must approach it with open minds

**Comment by GitDave99** [comment]
Downloaded 6.1.8

Testing...

**Comment by GitDave99** [comment]
Preliminary result:

1) looks like 6.2.1 may be off the hook, so to speak. Noise persists!

2) I have 5 P2 Edge cards. Another card shows same issue on compilation
with 618.

3) the "mystery " of the issue suddenly appearing ONLY in FlexProp v621
remains.

It may be "the last thing I did"

I've been running 24/7 on the same card at 320MHz with zero issues on two
projects.

But I will do the due diligence... we'll  see what eliminates the ADC noise
issue appearing only in compiled code.

I take your point about compiled code being essentially the same from these
two versions.

**Comment by Wuerfel21** [comment]
> I don't think the P2 Edge is reliable at 320 MHz, although it might be worth checking this on the forums.

The CPU/memory cores are stable at 320Mhz, but the ADC might not work properly when overclocking.

**Comment by GitDave99** [comment]
Chip said today it was designed to work at 200MHz.

He gave me some  things to try.

BUT!!! We cannot escape one fact: no noise in Proptool spin code. Big noise
in FP compiled code.

There may or may not be causality, but it remains a fact.

I'll  be doing more tests as time allows.

**Comment by GitDave99** [comment]
I can try changing the system clock on the fly. 200MHz de hile ADC active
for 20mS, 320MHz rest of the time

**Comment by GitDave99** [comment]
Hi Eric,

I was successful at doing dynamic sysclk control in PASM2.

It drops to 200MHz during ADC operation and then jumps back to 320MHz until
time to ADC again.

That lowered the "noise" in interesting ways.

Spin2, noise levels = 0,3,4 at 320MHz
Spin2, noise levels = 0,1,3 at 200MHz
FP, no opt     levels = 0,8,10    {these are the values the ADC outputs
w/no input signal}
FP, def opt    levels = 0,15,17
FP, size opt  levels = 0,5,7
FP, full opt    levels = 0,3,4

These results with ADC clock = 200MHz.

Why does optimization settings change noise levels? Very weird.

But.... I'm using HDMI for display and guess what? HDMI don' do no clock
swapping!
Got to have constant clock for hte HDMI and it needs to be at or above
300MHz to work
properly (for my graphic needs).

So, no clock freq swapping allowed. Too bad.

How to analyze this? I get that the compiler has some influence (by cause
and effect) on the ADC performance (by increasing jitter from hub accesses?
Other?)

I can't drop the clock to 200MHz for the HDMI function, must be 320MHz.
I guess I'll have to translate my spin code to pasm. Not hard, just time
consuming.

Any ideas? Thanks for fixing the looping issue! Works great.

Regards,
Dave

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by totalspectrum** [comment]
I'm not sure why you would translate your Spin2 code to PASM, that's what FlexProp does for you automatically. I think it may be more fruitful to examine the ADC code itself.

My guess is that there is indeed some kind of conflict between the ADC COG and the main COG, possibly hub ram contention. I notice that the D_S ADC 2.spin2 code is using WRBYTE to write individual samples at a time to HUB in two seperate arrays (left and right). If you could interleave the left and right channels you'd be able to use WRWORD or even better WFWORD to speed up the hub writes. You've also got a couple of QDIV/GETQX back to back in that code, which could again be sped up by doing some calculations for the other channel while the QDIV is going on.

Finally, and perhaps most important (?) there's a WAITX ##152 to "adjust sample rate for n samples in 20 mS". Wouldn't it be much better to use a WAITCT to guarantee the timing of the loop? With WAITCT you can be sure of how many cycles the loop is taking, with WAITX the total loop time depends on the time for other operations, including CORDIC and HUB, which could be disturbed by what other COGs are doing.

**Comment by Wuerfel21** [comment]
> including CORDIC and HUB, which could be disturbed by what other COGs are doing.

FYI, they generally can't. Each cog in itself should have deterministic timing.

**Comment by GitDave99** [comment]
Hi, Y'all

A long discussion with Chip yesterday about the role of jitter in the
operation of the Delta-sigma ADC plus the experience I got working with
compiler led me to believe that jitter is indeed the author of the "noise".

Looking at the timing of the ADC inner loop does show some  jitter. I'm
beginning to believe that the compiled code, running in HUB RAM, is
exacerbating jitter by more hub access than SPIN code. That's the only
mechanism I can see that would influence a cog running PASM2.

That seems supported by the way various compiler optimizations influence
noise.

I think Eric's points are well made. Chip also suggested ways to eliminate
jitter from the ADC driver code; no CORDIC, WRFAST, etc.

I'll be implementing these changes and expect good results.

The Delta-sigma ADC is a hybrid of hardware  and software, thus vulnerable
to jitter caused by HUB access and pipeline delays. Thus amenable to fixes
that reduce these jitter causing  delays.

Funny thing, after running the compiled code that changed the sysclk from
320MHz to 200MHz while the ADC worked and then back to 320MHz when ADC
done, running compiled code at 320MHz alone was much quieter, rivaling
operation in Spin code at that clock rate.

I have no idea why.

**Comment by GitDave99** [comment]
By the way, I've successfully translated SPIN to PASM with much larger code
than I'm working with now, that translation entirely fit in one cog.

The code was deterministic, maintainable and faster by far than PASM  in
HUB RAM.

Yes, the compiler is convenient for sure! But the effort to translate was
not great once the SPIN was sufficiently mature to reduce edits to small,
infrequent bouts in PASM.

Thanks for the compiler! As time goes on, I will be making good use of it.

**Comment by GitDave99** [comment]
Hi, Y'all!

So, I used WAITCT for ADC loop timing. Haven't used other jitter reduction
schemes yet, one step at a time.

Here's my observation: While the Spin2 code working in PropTool, the timing
of Pin0, which allows measuring ADC loop time with a logic analyzer,  is
very steady at 1uS per loop.
Compiling and launching with full optimization in FlexProp, the 1uS timing
varies! Faster, slower, mostly slower. That variation is bound to create
some issues with jitter, it seems.

This seems to be an indication that running PASM2 in HUB RAM does hog HUB
resources to some extent.

This may be reduced by implementing more jitter reduction schemes. No
CORDIC for instance (but that's a pipeline issue, not a HUB access issue,
right?). One step at a time!

In a past P1 project, I used 7 of the 8 cogs all running PASM. The cogs'
HUB access timing was pretty constant, once the cogs found their place in
the queue. Then I added more accesses to HUB RAM and succeeded in stalling
the HUB! Well, maybe not "stalling", but operations went south. I forget
the symptoms, it was 10 years ago!

**Comment by Wuerfel21** [comment]
There is no hogging of hub resources between cogs. There just isn't. Stop thinking about it, it's a dead end.

The thing to possibly focus on here is layout. Hub access timing depends on address LSBs, which may cause surprising timing funnies if the relative alignment of two accessed regions changes or hub access is intermingled with CORDIC ops (which have constant alignment)

Though idk why it would be inconsistent within one binary. Probably bug.

**Comment by GitDave99** [comment]
Well, okay, but my experience with the P1 begs to differ in one extreme
instance.

I had to back off from the added feature that overburdened the HUB. Yes, I
agree that normally  there should be no cog-cog interaction through the HUB.

I wonder why in Spin/proptool, the 1uS ADC loop timing is extremely solid,
even 300 uS after the trigger (when loop starts) there is no jitter. Rock
solid and accurate within the limits of my 200MHz logic analyzer. (Using
WAITCT)

Compile that same code, full opto, even in the first 10 ADC loops, the
timing varies.

I don't know enough about the compiler or PASM2 running in HUB RAM to do
more than hypothesize... what's your take?

**Comment by Wuerfel21** [comment]
> Well, okay, but my experience with the P1 begs to differ in one extreme
instance.

P1 is even more determinsitic. You did something wrong 10 years ago (possibly including using the illegal WZ flag from WRxxxx which _is_ known to be glitchy based on other cog's activity).

**Comment by GitDave99** [comment]
okay, that was an artifact of screen resolution in the LA making the timing
for compiled look worse than it was. didn't appear for SPIN so it fooled
me..

Zooming in shows that there is really no big difference between the SPIN
and compiled timing in ADC PASM loop.
At 300uS, the 300th loop pulse appeared 20nS later than the SPIN2/proptool
code.

My bad, jumping to conclusions is a bad habit.

**Comment by GitDave99** [comment]
LOLOL, yeah, I asked the HUB to handle more traffic than it could! No, I
didn't use the WZ. Never knew about that bug.

The app was using 3 cogs to create 40x30 tiles of 16x16 pixels in 4096
colors (RDAC for each R,G,B, 4 bits) written in PASM
Three more cogs were processing data to create color intensity values in
real time, writing to 3 video buffers in HUB ram. The 3 video cogs used
Vblanking time to read and load the video data into the cog register space
prior to writing it to the DACs.

A 7th cog was trying to do some more processing on the data reading from
hub, chewing on it and writing to hub... that wrecked the HUB timing in
some way I don't remember, but it wasn't good for the app! Just clogged
coggeries.

**Comment by totalspectrum** [comment]
It sounds like this has been resolved...
