### ISSUE TITLE
Compiling a previously successful C++ project after Ventura 13.3 SW Update & Cmd Line Tool updates, reports "error: unknown type name 'nullptr_t'"

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#79]
Sorry to re-introduce this issue, but I have gotten a response from the Apple Developer group at Apple...

After I described (to Apple) that this issue comes up after updating to macOS Ventura 13.3 (from 13), I got this response:

> Hello Dennis,
> 
> Thank you for filing the feedback report. 
> 
> From the logs, we can see that C Standard Library headers like /usr/local/include/stdlib.h are being used. Those are not the C Standard Library headers provided in the Apple SDK, and that is most likely the issue. The C++ Standard Library provided in the Apple SDK needs to be used on top of the C Standard Library provided in the Apple SDK. Please make sure to use the Apple SDK C Library and let us know if compiling that way still fails.
> 
> If the issue is resolved, you can close this feedback by selecting “Close Feedback” via the Actions button found above. If we don’t hear from you in the next two weeks, we’ll assume the issue is resolved or not reproducible and will consider this issue closed. After this time, you can create a new Feedback report if the issue remains. Thank you.

Does this mean that the PropLoader Makefile could be modified to work? The path to the SDK include directory is: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

I'm kind of clueless on this as I thought the include path for system library code would be a default in my OS environment. Do I need to update my paths in .zshrc or .bashrc? You can just close this issue if I'm way off on posting this issue.

Here is the compile log I reported that gave the errors:
[nullPtr_Errors.txt](https://github.com/totalspectrum/flexprop/files/12384210/nullPtr_Errors.txt)

**Comment by totalspectrum** [comment]
Hmmm, I honestly don't know what's happening here. Is it possible that you've installed a third party compiler (like gcc) or libraries through another channel, like homebrew, and that's conflicting with Apple's SDK? I can't run Ventura on my Mac Mini, so I'm afraid I can't really test this myself.

**Comment by dgately** [comment]
I had to remove or rename all references (soft links & MacOSX SDK directories) to MacOSX13.3.sdk in order to build proploader, within XCode's app package. Will most likely not be able to build XCode projects without replacing the links & proper filenames to the SDK path, though. But, proploader now builds :-)
