### ISSUE TITLE
Building flexprop on recent RPi OS (Bookworm) requires xxd, which is not installed

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#83]
Among several other failures in building flexprop 6.6.1 from source on latest Raspberry Pi OS (Bookworm), it appears that xxd is no longer part of the default RPi OS installation and needs to be installed via apt.

The fix: 
`$ sudo apt install xxd`   

Useful info:
```
$ uname -a
Linux rpi4-64 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux

$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by totalspectrum** [comment]
Thank you. I've added xxd to the list of required modules for installation, and that should fix a lot of the problems you encountered.
