### ISSUE TITLE
Building flexprop (6.6.1) on latest RPi OS requires previously built .bin objects

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexprop#84]
During a fresh build of flexprop 6.6.1 on RPi OS Bookworm fails during the loadp2 build process. The build requires 2 binary files that should have built from .spin2 code via flexspin (source: P2ES_flashloader.spin2). Due possibly to another issue (to be written up), these files don't get built:

- P2ES_flashloader.bin
- P2ES_sdcard.bin

To quickly get past this issue, I retrieved copies of those files from a previously built flexprop (pre-Bookworm built). This allowed compiling loadp2.c to go further (but, not successfully). 

Useful info:

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
$ uname -a
Linux rpi4-64 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux
```

**Comment by totalspectrum** [comment]
I think this was an artifact of your not having xxd when first trying to build. I just ran the flexprop build process (with the updated instructions including xxd) on a newly formatted raspberry pi SD card and it finished without any issues.
