### ISSUE TITLE
Iostream 

### ISSUE THREAD

**Issue by Foxtfour** [totalspectrum/flexprop#88]
Loading flexprop 6.8.0 does not populate include folder with iostream header file.  This fails to debug when compiling.

**Comment by Wuerfel21** [comment]
There is no iostream header because there is no full C++ support, only regular C (and if there were c++ support, using iostream would immediately fill your entire RAM with horrible bloatware)

**Comment by Foxtfour** [comment]
Thanks for the immediate response!  Understand to use regular C.

Appreciate your help!

**Comment by totalspectrum** [comment]
Yes, I don't think we want to try to support the STL. The compiler only understands a tiny subset of C++ at the moment.
