### ISSUE TITLE
Command shell menu item is broken

### ISSUE THREAD

**Issue by Wuerfel21** [totalspectrum/flexprop#89]
The menu item to launch command shell throws an error. Happens with current version 6.8.0 on Win as well as the slightly old version I have installed on Linux.

Happened to find this out live on live forum today. We got chip to install flexprop live on stream, deeply funny, watch the replay when it's out (if they don't cut that part... really long)

**Comment by Wuerfel21** [comment]
the flexprop installation experience: https://youtu.be/277iRo9EC1w?t=13206

> Chip: It's gonna be like an adventure
> Me: No, it's actually very easy

...

**Comment by totalspectrum** [comment]
Wow, that was a nightmare. I haven't been able to reproduce the download problem (Chrome, Firefox, and Edge are all happy to download the .zip on my Windows machine) but I did try submitting to an online virus scanner and 2 out of 65 scanners complained about the file (and about the source code .zip too!). My guess is that something in the Tcl/Tk runtime makes some virus scanner unhappy, there may be some compressed code or something. Not sure what I can do about that :(.

**Comment by Wuerfel21** [comment]
The issue wasn't just flexprop, he couldn't download any files at all. No problem on your end :)

**Comment by totalspectrum** [comment]
I've removed the command shell menu item; it was indeed broken and maintaining it is probably not worth it... better for the user to compile the shell on their own machine (the source is there, after all).
