### ISSUE TITLE
Relative jump address bug in cog mode (flexspin)

### ISSUE THREAD

**Issue by bartgrantham** [totalspectrum/flexprop#90]
I'm not sure if this is a bug, or I've misunderstood the manual, but I think when in `org` mode (cog mode) relative addresses in jumps should be cog-relative, not hub-relative.

`test.spin2`:
```
dat
org 0
.halt  jmp #.halt
```

After assembling with `flexspin -2 -l test.spin2`, `test.lst`:
```
00000                 |
00000                 | #line 1 "test.spin2"
00000                 | dat
00000 000             | org 0
00000 000             | .halt  jmp #.halt
00000 000 FC FF 9F FD
00004 001             |
```

```
'   FC FF 9F FD  =>  FD 9F FF FC  =>  1111 1101100 111 111111111 111111100
'  JMP  #{\}A  |  Branch A - Jump   | EEEE 1101100 RAA AAAAAAAAA AAAAAAAAA
```

That bit pattern shows a address offset of -4, I was expecting -1.  I'm using flexspin v6.8.0.

**Comment by Wuerfel21** [comment]
I think I ran into this at some point. It just works like that, I think it ignores the bottom 2 bits. This is actually a design feature, since it makes it possible to relocate code segments between cog and hub.

**Comment by bartgrantham** [comment]
After some discussion on Discord I figured I should share why I expected cog mode to behave differently.  The "v35" manual has under "BRANCH ADDRESSING":

> The JMPREL instruction uses D as a relative address that steps whole instructions. In cog mode, D[19:0] is added to the program counter and in hub mode, D[17:0] << 2 is added to the program counter. This instruction is unique in its ability to make a relative jump (as opposed to an absolute jump) based on a register value. If #D is used, the relative address will be a positive 9-bit value:
>
> `EEEE 1101011 00L DDDDDDDDD 000110000        JMPREL  {#}D`

And then under "Assembly Language":

```
    ORGH    {hub_address}

    Set hub mode and an optional address to fill to with $00 bytes.


    ORG     {cog_address {,cog_address_limit}}

    Set cog mode with optional cog address and limit. Defaults to $000,$200.
    If $200..$3FF used for cog address, LUT range selected. Doesn't generate
    any data.
```

The first part tells me that cog and hub addressing is different, and the second part tells me that the `ORG` and `ORGH` directives define what addressing mode should be used.

Looking at the spreadsheet and noticing that there are _two_ `JMP` instructions, I guess I was expecting either an absolute or relative "Branch D - Jump", rather than the "Branch A - Jump" that it produced.

**Comment by totalspectrum** [comment]
The JMPREL instruction is, confusingly, not the relative version of the JMP instruction. JMPREL is much more complicated, it adds the offset to the current PC and then loads the new address to jump to from there.

I can assure you that the encoding of relative JMP instructions in both COG and HUB memory is correct in flexspin. If it weren't, no code would run correctly (JMP is used a *lot*, and usually in its relative form) and in fact we have automatic tests that compare flexspin's output with PNut's. Indeed, if you ever suspect an error in flexspin's instruction encoding I would encourage you to compare what PNut does.

**Comment by bartgrantham** [comment]
> The JMPREL instruction is, confusingly, not the relative version of the JMP instruction.

Rereading the docs just now, I can see that I misunderstood that passage.

For anyone who comes across this issue under the same misunderstanding that I had, I followed @totalspectrum's advice and checked what PNut v43 produces, and it indeed generates the exact same:

```
00000- FC FF 9F FD                                       '....'
```

I apologize for the confusion.
